### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by bhavyakamboj** [arn4v/covid-resources#1]
![image](https://user-images.githubusercontent.com/676770/117550663-2095c500-b05f-11eb-99f4-173223e75121.png)

After adding firebase credentials, getting build error

`info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[  ==] info  - Generating static pages (0/3)
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getStaticProps (/home/bhavya/IdeaProjects/covid/covid-resources/.next/server/pages/index.js:3212:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
info  - Generating static pages (3/3)

> Build error occurred
Error: Export encountered errors on following paths:
        /
    at nextExportSpan.traceAsyncFn (/home/bhavya/IdeaProjects/covid/covid-resources/node_modules/next/dist/export/index.js:31:1106)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! covid-resources@0.1.0 build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the covid-resources@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bhavya/.npm/_logs/2021-05-08T19_11_05_341Z-debug.log`

Detailed logs

0 info it worked if it ends with ok
1 verbose cli [ '/home/bhavya/.nvm/versions/node/v10.21.0/bin/node',
1 verbose cli   '/home/bhavya/.nvm/versions/node/v10.21.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.14.4
3 info using node@v10.21.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle covid-resources@0.1.0~prebuild: covid-resources@0.1.0
6 info lifecycle covid-resources@0.1.0~build: covid-resources@0.1.0
7 verbose lifecycle covid-resources@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle covid-resources@0.1.0~build: PATH: /home/bhavya/.nvm/versions/node/v10.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/bhavya/IdeaProjects/covid/covid-resources/node_modules/.bin:/home/bhavya/.deno/bin:/usr/lib/jvm/jdk1.8.0_221/bin:/home/bhavya/Android/Sdk/emulator:/home/bhavya/Android/Sdk/tools:/home/bhavya/Android/Sdk/platform-tools:/home/bhavya/Android/Sdk/tools/bin:/home/bhavya/.deno/bin:/usr/lib/jvm/jdk1.8.0_221/bin:/home/bhavya/Android/Sdk/emulator:/home/bhavya/Android/Sdk/tools:/home/bhavya/Android/Sdk/platform-tools:/home/bhavya/Android/Sdk/tools/bin:/home/bhavya/.sdkman/candidates/groovy/current/bin:/home/bhavya/.sdkman/candidates/gradle/current/bin:/home/bhavya/.nvm/versions/node/v10.21.0/bin:/home/bhavya/.npm-global/bin:/home/bhavya/bin:/home/bhavya/.local/bin:/opt/maven/bin:/usr/lib/jvm/jdk1.8.0_221/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/jdk1.8.0_151/bin:/usr/lib/jvm/jdk1.8.0_151/db/bin:/usr/lib/jvm/jdk1.8.0_151/jre/bin:/opt/Postman/:/snap/bin:/usr/local/go/bin:/home/bhavya/work/bin:/usr/spark/spark-2.4.6-bin-hadoop2.7/bin:/usr/local/hadoop/bin:/usr/share/logstash/bin:/usr/spark/spark-2.4.6-bin-hadoop2.7/bin:/usr/local/hadoop/bin:/usr/share/logstash/bin
9 verbose lifecycle covid-resources@0.1.0~build: CWD: /home/bhavya/IdeaProjects/covid/covid-resources
10 silly lifecycle covid-resources@0.1.0~build: Args: [ '-c', 'next build' ]
11 silly lifecycle covid-resources@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle covid-resources@0.1.0~build: Failed to exec build script
13 verbose stack Error: covid-resources@0.1.0 build: `next build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/bhavya/.nvm/versions/node/v10.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/bhavya/.nvm/versions/node/v10.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid covid-resources@0.1.0
15 verbose cwd /home/bhavya/IdeaProjects/covid/covid-resources
16 verbose Linux 5.4.0-72-generic
17 verbose argv "/home/bhavya/.nvm/versions/node/v10.21.0/bin/node" "/home/bhavya/.nvm/versions/node/v10.21.0/bin/npm" "run" "build"
18 verbose node v10.21.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error covid-resources@0.1.0 build: `next build`
22 error Exit status 1
23 error Failed at the covid-resources@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by arn4v** [comment]
Hi Bhavya, covid-resources is now https://covid.army. The codebase for the new site can be found here: https://github.com/covidarmy/frontend
